import './globals.css';
import type { Metadata } from 'next';
import tomorrowHomeIcon from '../../public/tomorrow-home.svg';
import Image from 'next/image';
import Link from 'next/link';
import { pretendard } from '@/utils/variables';
import localFont from 'next/dist/compiled/@next/font/dist/local';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <nav>
        <div className="max-w-[1256px] mx-auto h-[80px] py-[10px] px-[60px] flex items-center">
          <Link href="/">
            <Image src={tomorrowHomeIcon} alt="" width={74} height={30} />
          </Link>
        </div>
      </nav>
      <body className="font-normal">{children}</body>
    </html>
  );
}
