import { NextResponse } from 'next/server';

export const GET = () => {
  try {
    return NextResponse.json([
      {
        id: 1,
        is_scrap: false,
        is_wish: false,
        type: 'Production',
        badges: [],
        benefit_badges: [
          {
            image:
              'https://image.ohou.se/i/bucketplace-v2-development/static/productions/card-promotion-badge.png?w=40&h=32',
            title: '최대 5% 결제할인',
            ozip_title: '최대 5% 결제할인',
            discount_ratio: '5',
            fixed_discount_amount: null,
            promotion_payment_method: 'KAKAO_PAY',
          },
        ],
        brand: {
          id: 1,
          name: '코튼리빙',
        },
        brand_id: 1,
        brand_name: '코튼리빙',
        cost: 100000,
        coupon_badge: {
          image:
            'https://image.ohou.se/i/bucketplace-v2-development/static/productions/goods-coupon-badge.png',
          title: '할인쿠폰',
          discount_ratio: null,
          fixed_discount_amount: null,
        },
        delivery_service_code: 'SELLER',
        delivery_start_at: {
          template: {
            text: '평일 %s까지 결제시',
            values: ['13:00'],
          },
        },
        delivery_type: 0,
        free_delivery: true,
        image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/168731059927618146.jpg?gif=1&w=360&h=360&c=c&q=0.8&webp=1',
        is_bespoke: false,
        is_buyable: true,
        is_cheapest_price: false,
        is_consultable: false,
        is_delivery_date_specified: false,
        is_departure_today: true,
        is_discontinued: false,
        is_discounted: false,
        is_free_delivery: true,
        is_hidden: false,
        is_overseas_purchase: false,
        is_remodel: false,
        is_retail_delivery: false,
        is_selling: true,
        is_sold_out: false,
        is_special_price: true,
        is_third_party_logistic: false,
        lowest_guarantee: false,
        name: '[9/18하루27,900원](후기5만돌파) 40수 코마사 호텔수건 200g 10장',
        original_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/168731059927618146.jpg?gif=1&w=360&h=360&c=c&q=0.8&webp=1',
        original_price: 100000,
        raw_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/168731059927618146.jpg?gif=1&w=360&h=360&c=c&q=0.8&webp=1',
        resized_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/168731059927618146.jpg?gif=1&w=360&h=360&c=c&q=0.8&webp=1',
        review_avg: 4.7,
        review_count: 58884,
        scrap_count: 403,
        selling: true,
        selling_cost: 29900,
        selling_price: 29900,
        sold_out: false,
        status: 4,
        used_card_count: 372,
        user_id: 1253497,
        view_count: 0,
        week_rank: 0,
        wish_count: 403,
      },
      {
        id: 2,
        is_scrap: false,
        is_wish: false,
        type: 'Production',
        badges: [],
        benefit_badges: [
          {
            image:
              'https://image.ohou.se/i/bucketplace-v2-development/static/productions/card-promotion-badge.png?w=40&h=32',
            title: '최대 5% 결제할인',
            ozip_title: '최대 5% 결제할인',
            discount_ratio: '5',
            fixed_discount_amount: null,
            promotion_payment_method: 'KAKAO_PAY',
          },
        ],
        brand: {
          id: 2,
          name: '헬로우슬립',
        },
        brand_id: 2,
        brand_name: '헬로우슬립',
        cost: 60000,
        coupon_badge: {
          image:
            'https://image.ohou.se/i/bucketplace-v2-development/static/productions/goods-coupon-badge.png',
          title: '할인쿠폰',
          discount_ratio: null,
          fixed_discount_amount: null,
        },
        delivery_service_code: 'SELLER',
        delivery_start_at: null,
        delivery_type: 0,
        free_delivery: true,
        image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/deals/169496486451930009.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        is_bespoke: false,
        is_buyable: true,
        is_cheapest_price: false,
        is_consultable: false,
        is_delivery_date_specified: false,
        is_departure_today: false,
        is_discontinued: false,
        is_discounted: false,
        is_free_delivery: true,
        is_hidden: false,
        is_overseas_purchase: false,
        is_remodel: false,
        is_retail_delivery: true,
        is_selling: true,
        is_sold_out: false,
        is_special_price: true,
        is_third_party_logistic: false,
        lowest_guarantee: false,
        name: '[단하루!할인+10%쿠폰] 최대혜택! 헬로우슬립 가을 이불/패드/매커~78%',
        original_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/deals/169496486451930009.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        original_price: 60000,
        raw_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/deals/169496486451930009.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        resized_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/deals/169496486451930009.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        review_avg: 4.7,
        review_count: 24838,
        scrap_count: 403,
        selling: true,
        selling_cost: 33900,
        selling_price: 33900,
        sold_out: false,
        status: 4,
        used_card_count: 372,
        user_id: 1253497,
        view_count: 0,
        week_rank: 0,
        wish_count: 403,
      },
      {
        id: 3,
        is_scrap: false,
        is_wish: false,
        type: 'Production',
        badges: [],
        benefit_badges: [
          {
            image:
              'https://image.ohou.se/i/bucketplace-v2-development/static/productions/card-promotion-badge.png?w=40&h=32',
            title: '최대 5% 결제할인',
            ozip_title: '최대 5% 결제할인',
            discount_ratio: '5',
            fixed_discount_amount: null,
            promotion_payment_method: 'KAKAO_PAY',
          },
        ],
        brand: {
          id: 3,
          name: '에이트룸',
        },
        brand_id: 3,
        brand_name: '에이트룸',
        cost: 100000,
        coupon_badge: {
          image:
            'https://image.ohou.se/i/bucketplace-v2-development/static/productions/goods-coupon-badge.png',
          title: '할인쿠폰',
          discount_ratio: null,
          fixed_discount_amount: null,
        },
        delivery_service_code: 'SELLER',
        delivery_start_at: null,
        delivery_type: 0,
        free_delivery: true,
        image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/168774136219290693.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        is_bespoke: false,
        is_buyable: true,
        is_cheapest_price: false,
        is_consultable: false,
        is_delivery_date_specified: false,
        is_departure_today: false,
        is_discontinued: false,
        is_discounted: false,
        is_free_delivery: true,
        is_hidden: false,
        is_overseas_purchase: false,
        is_remodel: false,
        is_retail_delivery: false,
        is_selling: true,
        is_sold_out: false,
        is_special_price: true,
        is_third_party_logistic: false,
        lowest_guarantee: false,
        name: '[단하루!할인+10%쿠폰] 최대혜택! 헬로우슬립 가을 이불/패드/매커~78%',
        original_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/168774136219290693.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        original_price: 100000,
        raw_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/168774136219290693.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        resized_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/168774136219290693.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        review_avg: 4.7,
        review_count: 6634,
        scrap_count: 403,
        selling: true,
        selling_cost: 69900,
        selling_price: 69900,
        sold_out: false,
        status: 4,
        used_card_count: 372,
        user_id: 1253497,
        view_count: 0,
        week_rank: 0,
        wish_count: 403,
      },
      {
        id: 4,
        is_scrap: false,
        is_wish: false,
        type: 'Production',
        badges: [],
        benefit_badges: [
          {
            image:
              'https://image.ohou.se/i/bucketplace-v2-development/static/productions/card-promotion-badge.png?w=40&h=32',
            title: '최대 5% 결제할인',
            ozip_title: '최대 5% 결제할인',
            discount_ratio: '5',
            fixed_discount_amount: null,
            promotion_payment_method: 'KAKAO_PAY',
          },
        ],
        brand: {
          id: 4,
          name: '다룸',
        },
        brand_id: 4,
        brand_name: '다룸',
        cost: 160000,
        coupon_badge: {
          image:
            'https://image.ohou.se/i/bucketplace-v2-development/static/productions/goods-coupon-badge.png',
          title: '할인쿠폰',
          discount_ratio: null,
          fixed_discount_amount: null,
        },
        delivery_service_code: 'SELLER',
        delivery_start_at: null,
        delivery_type: 0,
        free_delivery: true,
        image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/169050673707032945.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        is_bespoke: false,
        is_buyable: true,
        is_cheapest_price: false,
        is_consultable: false,
        is_delivery_date_specified: false,
        is_departure_today: false,
        is_discontinued: false,
        is_discounted: false,
        is_free_delivery: true,
        is_hidden: false,
        is_overseas_purchase: false,
        is_remodel: false,
        is_retail_delivery: false,
        is_selling: true,
        is_sold_out: false,
        is_special_price: true,
        is_third_party_logistic: false,
        lowest_guarantee: false,
        name: '[단하루!할인+10%쿠폰] 최대혜택! 헬로우슬립 가을 이불/패드/매커~78%',
        original_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/169050673707032945.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        original_price: 160000,
        raw_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/169050673707032945.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        resized_image_url:
          'https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/169050673707032945.jpg?gif=1&w=360&h=360&c=c&q=0.8',
        review_avg: 4.7,
        review_count: 76,
        scrap_count: 403,
        selling: true,
        selling_cost: 67000,
        selling_price: 67000,
        sold_out: false,
        status: 4,
        used_card_count: 372,
        user_id: 1253497,
        view_count: 0,
        week_rank: 0,
        wish_count: 403,
      },
    ]);
  } catch {
    return NextResponse.json(
      { error: '문제가 발생했습니다. 다시 시도해 주세요.' },
      { status: 500 }
    );
  }
};
